### ISSUE TITLE
Styling Concerns

### ISSUE THREAD

**Issue by brianbodollo** [srph/react-redux-starter-kit#27]
I'm new on using `Autoprefixer` and `CSSNano` and don't have idea on how they work. Do the prefixing and minifying happens when you run `build:style`/`prod:style` or do I need to setup config and add them as a loader on `webpack` for them to work?

**Comment by srph** [comment]
No, PostCSS does them. PostCSS is similar to Webpack. What it does is bundle CSS (but it's not for this setup; Sass does that for us), and Autoprefixer and CSSNano are similar to Webpack's loaders. Difference is that Sass is a (cross-platform) stand-alone tool that doesn't rely on PostCSS to work.

As you can see, I don't have any configuration file because the setup is pretty simple, and that I'm using the [cli](https://github.com/srph/react-redux-starter-kit/blob/master/package.json#L9). PostCSS has a [node API if you want to pass custom configurations](https://github.com/postcss/postcss#js-api).

To elaborate further, it's possible to use PostCSS in Webpack. This makes sense if you're going to use CSS-in-JS (stuff similar to [Radium](https://github.com/FormidableLabs/radium))
